### ISSUE TITLE
app下载地址

### ISSUE THREAD

**Issue by dcxy0** [70kg/Meizi#1]
建议把下载地址给上:http://fir.im/b49u

**Comment by 70kg** [comment]
@dcxy0 谢谢  请问你是在哪看到这个开源地址的。。

**Comment by dcxy0** [comment]
csdn看到的，建议修改一下保存方式。没必要提示了的。

**Comment by 70kg** [comment]
@dcxy0 谢谢 我觉得还是应该提示一下保存成功。
