### ISSUE TITLE
请教一个问题啊

### ISSUE THREAD

**Issue by kyleada** [70kg/Meizi#3]
先点赞！
这个版本在转到GroupActivity后，图片加载速度确实大幅提高了，看了下commit对比之前的，没有发现关键点，能指点下吗？
谢谢~

**Comment by 70kg** [comment]
@kyleada 先感谢你看了代码，其实之前每张图片都会去抓取一遍网页，只为了去获取一个图片的URL，效率很低，现在找到了图片URL的规律就不用去请求一遍网页了，只要去加载图片就可以。具体可以看一下newLoadData()和newHandleContent方法。欢迎提意见，共同学习
