### ISSUE TITLE
少了很多张资源图片口阿

### ISSUE THREAD

**Issue by qq137712630** [70kg/Meizi#4]
目前无法编译，可不可以帮忙上传一下这些文件？

	Meizi\meizi_retrofit\src\main\res\layout\about.xml
	Error:(37, 26) No resource found that matches the given name (at 'src' with value '@drawable/test').
	Error:(98, 42) No resource found that matches the given name (at 'src' with value '@drawable/ic_github').
	Error:(127, 42) No resource found that matches the given name (at 'src' with value '@drawable/weibo').
	Meizi\meizi_retrofit\src\main\res\menu\group_menu.xml
	Error:(6, 23) No resource found that matches the given name (at 'icon' with value '@drawable/collect').
	Meizi\meizi_retrofit\src\main\res\menu\menu_drawer.xml
	Error:(39, 27) No resource found that matches the given name (at 'icon' with value '@drawable/ic_tag').
	Error:(44, 27) No resource found that matches the given name (at 'icon' with value '@drawable/menu_collect').
	Meizi\meizi_retrofit\src\main\res\menu\searchmenu.xml
	Error:(6, 23) No resource found that matches the given name (at 'icon' with value '@drawable/ic_search').
	Error:Execution failed for task ':meizi_retrofit:processBaiduDebugResources'.
	> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\Android\adt-bundle-windows-x86-20140702\sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1

**Comment by 70kg** [comment]
@qq137712630  sorry，现在可以了

**Comment by qq137712630** [comment]
谢谢
