### ISSUE TITLE
Project: meizi # question

### ISSUE THREAD

**Issue by rfyiamcool** [70kg/Meizi#8]
肉丝，黑丝啥的

**Comment by 70kg** [comment]
？？

**Comment by jpg1024** [comment]
Python我会，服务器我有，就是流量不多，放图片太费流量了。70kg你试试七牛和又拍云可以放不。或者试试搬瓦工也可以。搬瓦工比较便宜，速度有点慢。

**Comment by 70kg** [comment]
这些是从网上扒拉的图片，就是放在自己服务器上也只是存储URL，又不占空间。。 @dcxy0
